AWSTemplateFormatVersion: 2010-09-09
Description: Public EC2 instance module

Parameters:
  InstanceTypeParameter: # Configuration for VPC
    Type: String
    Default: t3.micro
    AllowedValues:
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
    Description: Configuration for VPC

  ImageIDParameter: # Create ImageID parameter
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
  
  KeyNameParameter: # Create KeyName 
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

  PublicInstanceSecurityGroupSubnetId:
    Description: This is Subnet ID of PublicInstanceSecurityGroupSubnet
    Type: String

  PrivateInstanceSecurityGroupSubnetId:
    Description: This is Subnet ID of PrivateInstanceSecurityGroupSubnet
    Type: String
  
  PublicSubnetId:
    Description: This is Public subnet ID 
    Type: AWS::EC2::Subnet::Id

  PrivateSubnetId:
    Description: This is Private subnet ID 
    Type: AWS::EC2::Subnet::Id
    
Resources:
  ElasticIPInstance:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !GetAtt EC2PublicSubnetInstance.InstanceId

  EC2PublicSubnetInstance: # Create instance in public subnet
    Type: AWS::EC2::Instance 
    Properties:
      InstanceType: !Ref InstanceTypeParameter # Configuration for instance
      ImageId: !Ref ImageIDParameter
      KeyName: !Ref KeyNameParameter
      SecurityGroupIds:
        - !Ref PublicInstanceSecurityGroupSubnetId
      SubnetId: !Ref PublicSubnetId
      Tags:
        - Key: Name
          Value: Lab1_Group3_PublicInstance

  EC2PrivateSubnetInstance: # Create instance in private subnet
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceTypeParameter # Configuration for instance
      ImageId: !Ref ImageIDParameter
      KeyName: !Ref KeyNameParameter
      SecurityGroupIds:
        - !Ref PrivateInstanceSecurityGroupSubnetId
      SubnetId: !Ref PrivateSubnetId
      Tags:
        - Key: Name
          Value: Lab1_Group3_PrivateInstance

  