project:
    name: taskcat-scan-cloudformation
tests:
    stack-scan:
        regions:
            - us-east-1
        parameters:
            AvailabilityZones: $[taskcat_genaz_2]
            VPCName: VPC
            VPCCidr: 10.0.0.0/16
            PublicSubnetCidr: 10.0.0.0/24
            PrivateSubnetCidr: 10.0.1.0/24
            InstanceTypeParameter: t3.micro
            ImageIDParameter: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64
            KeyNameParameter: group3
        template: ./pipeline-stack.yml


    
    