version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing cfn-lint..."
      - pip install --upgrade pip
      - pip install cfn-lint
      - echo "Installing taskcat..."
      - pip3 install taskcat

  build:
    commands: 
      - echo "Scanning EC2 module..."
      - cfn-lint -t ./modules/ec2module.yml --info
      - echo "EC2 module scanned successfully!"
      
      - echo "Scanning Security Group module..."
      - cfn-lint -t ./modules/sgmodule.yml --info
      - echo "Security Group module scanned successfully!"
      
      - echo "Scanning VPC module..."
      - cfn-lint -t ./modules/vpcmodule.yml --info
      - echo "VPC module scanned successfully!"
      
      - echo "Scanning Nestedstack.yml..."
      - cfn-lint -t ./Nestedstack.yml
      - echo "Nestedstack.yml scanned successfully!"

      - echo "Scanning pipeline-stack.yml..."
      - cfn-lint -t ./pipeline-stack.yml
      - echo "pipeline-stack scanned successfully!"

      - echo "Taskcat scanning pipeline-stack.yml..."
      - taskcat test run 
      - echo "pipeline-stack is created in another region successfully!"
      
artifacts:
  files:
    - '**/*'
  name: Group3-$(date +%Y-%m-%d)
