AWSTemplateFormatVersion: 2010-09-09
Description: Create VPC, networking components, EC2, Security Group

Parameters:
  AvailabilityZones:
    Type: List<AWS::EC2::AvailabilityZone::Name>
    Description: The list of Availability Zones to use for the subnets in the VPC. Select 2 AZs.
  VPCName:
    Type: String
    Description: The name of the VPC.
    Default: cfn-workshop-vpc
  VPCCidr:
    Type: String
    Description: The CIDR block for the VPC.
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/16
  PublicSubnetCidr:
    Type: String
    Description: The CIDR block for the public subnet located in Availability Zone 1.
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/24
  PrivateSubnetCidr:
    Type: String
    Description: The CIDR block for the public subnet located in Availability Zone 2.
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.1.0/24
  InstanceTypeParameter:
    Type: String
    Description: Configuration for EC2 instance type
    Default: t3.micro
  AMIIDParameter:
    Type: String
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64
  KeyNameParameter:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
      

Resources:
  VPCModule: # Create VPC stack from module
    Type: AWS::CloudFormation::Stack 
    Properties: 
      TemplateURL: https://group3-bucket-s3.s3.us-east-1.amazonaws.com/vpcmodule.yml
      Parameters:
        AvailabilityZones:
          Fn::Join:
            - ','
            - !Ref AvailabilityZones
        VPCCidr: !Ref VPCCidr
        VPCName: !Ref VPCName
        PublicSubnetCidr: !Ref PublicSubnetCidr
        PrivateSubnetCidr: !Ref PrivateSubnetCidr
  
  SecurityGroupModule: # Create SecurityGroup stack from module
    Type: AWS::CloudFormation::Stack 
    Properties: 
      TemplateURL: https://group3-bucket-s3.s3.us-east-1.amazonaws.com/sgmodule.yml
      Parameters:
        VPCID: !GetAtt VPCModule.Outputs.VPCID
        PublicSubnetCidr: !Ref PublicSubnetCidr

  EC2Module: # Create EC2 stack from module
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://group3-bucket-s3.s3.us-east-1.amazonaws.com/ec2module.yml
      Parameters: 
        InstanceTypeParameter: !Ref InstanceTypeParameter
        ImageIDParameter: !Ref AMIIDParameter
        KeyNameParameter: !Ref KeyNameParameter
        PublicInstanceSecurityGroupSubnetId: !GetAtt SecurityGroupModule.Outputs.SecurityGroupPublicInstanceId
        PrivateInstanceSecurityGroupSubnetId: !GetAtt SecurityGroupModule.Outputs.SecurityGroupPrivateInstanceId
        PublicSubnetId: !GetAtt VPCModule.Outputs.PublicSubnet1
        PrivateSubnetId: !GetAtt VPCModule.Outputs.PrivateSubnet1
      

 

      



  


  

